### ISSUE TITLE
Incompatibility with Jello

### ISSUE THREAD

**Issue by floral-qua-floral** [Jack-Papel/Critical-Shears#1]
The game fails to launch when Critical Shears and [Jello](https://modrinth.com/mod/jello) are loaded together. The window never opens and no crash report is generated, however the latest.log file does have information about the error. It looks to me like it has something to do with both mods trying to modify interactions with sheep.

* Minecraft 1.19
* Fabric loader 0.14.8
* Fabric API 0.58.0
* Cloth Config 7.0.73
* oωo 0.7.3
* Jello 4.1.0
* Critical Shears 1.0.3

latest.log file: [latest.log](https://github.com/wisp-forest/Jello/files/9219071/latest.log)
Matching issue report on Jello's issue tracker: [Issue #15](https://github.com/wisp-forest/Jello/issues/15)

**Comment by Jack-Papel** [comment]
It looks like they fixed it on their end. Thanks for being patient - It seems I missed this in my notifications.
